### ISSUE TITLE
OpModeRegister

### ISSUE THREAD

**Issue by archishou** [ftctechnh/ftc_app#534] opened 2018-04-15 05:32 UTC
I'm having an issue where when I delete an opmode, the opmode still shows up on the phone. With the error of a duplicate opmode. I'm using annotations to register an opmode. Is there any fix for this? Thank you.

**Comment by NoahAndrews** [comment] 2018-04-15 11:41
Are you using OnBotJava?

**Comment by qwertychouskie** [comment] 2018-04-16 01:50
Probably a duplicate of https://github.com/ftctechnh/ftc_app/issues/517, try `Build->Clean Project`.

**Comment by archishou** [comment] 2018-04-16 12:36
Yup thank you!

**Closed** 2018-04-16 19:17 UTC
